AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  BuketName: 
    Type: String

Description: my template
Resources:
  MyLambda1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my-lambda-1
      Runtime: python3.6
      CodeUri: ./build
      Handler: my_lambda.handler
      Role: !GetAtt MyLambdaRole.Arn

Outputs:
  OuputValue1:
    Value: !Ref MyBucket